export { default as Book } from './book.svg?react'
export { default as Cross } from './cross.svg?react'
export { default as MapMarker } from './map-marker.svg?react'
export { default as Message } from './message.svg?react'
export { default as Pen } from './pen.svg?react'
export { default as Plus } from './plus.svg?react'
export { default as User } from './user.svg?react'
export { default as Map } from './map.svg?react'
