name: Running client tests

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/client-tests.yml'
      - 'client/**'

defaults:
  run:
    working-directory: ./client

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checking out code
        uses: actions/checkout@v4
      - name: Installing Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install packages
        run: npm ci
      - name: Build
        run: npm run build
  prettier:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checking out code
        uses: actions/checkout@v4
      - name: Installing Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install packages
        run: npm ci
      - name: Prettier
        run: npm run format:check
